spring.application.name=iTicket
# Data Base
server.port=${PORT}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Supabase
jwk.set.uri=${JWK_SET_URI}
jwt.issuer=${JWT_ISSUER}

cors.allowed-origins=${FRONTEND_URL}