spring.application.name=iTicket
# Data Base
server.port=${PORT}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.defer-datasource-initialization=false
spring.jpa.open-in-view=false

# Connection pool and timeout settings
spring.datasource.hikari.initialization-fail-timeout=1000
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.validation-timeout=1000

springdoc.swagger-ui.oauth.client-id=swagger-client

logging.level.web=WARN
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# Supabase
jwk.set.uri=${JWK_SET_URI}
jwt.issuer=${JWT_ISSUER}

# Startup Performance Optimizations
spring.jmx.enabled=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Lazy init all beans
spring.main.lazy-initialization=true

# Disable banner printing
spring.main.banner-mode=off

# Don’t waste time on JPA schema updates in production
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql=off
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.archive.autodetection=none

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false