# Core
spring.application.name=iTicket
server.port=${PORT}

# DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.archive.autodetection=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.packages-to-scan=dev.hiwa.iticket.model

# Connection pool
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.initialization-fail-timeout=1000
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.validation-timeout=1000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

# Performance
spring.main.lazy-initialization=true
spring.jmx.enabled=false
spring.main.banner-mode=off

# Logging
logging.level.web=WARN
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# Disable dev-only stuff
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
